- index.html
Series of patches which generally normalizes the document format and adds a slew of TODOs for what we still need to fill in.
> Move everything else into pre.idl blocks

- index.html
Read-only attributes should use FrozenArray and method parameters and
return values should use sequences.
This should resolve issue #9.
> Remove legacy array type from IDL.

- index.html
Per the discussion on blink-dev, this is probably what we want. Lack of NoInterfaceObject does not imply that we must provide a platform-accessible constructor, which was my previous interpretation.
> Remove [NoInterfaceObject] from most interfaces

- index.html
Per domenic's suggestion. I don't really think it would be a good idea for us to introduce device identifiers, so I'm still omitting a constructor for USBDevice itself. Do these look right to you?
> Add constructors for non-device types

- index.html
Based on recent discussions:
- Version changes are a compromise between a combined format and a separate version interface
- foo -> fooName for consistency (plus "interface" is not a valid identifier).
- Scrapped the isochronous endpoint interface. iso endpoints still visible, but support only control xfer
> Some changes to bring IDL up to speed

- index.bs
Same way Web Bluetooth does, this would allow users to add helper functions to their prototypes without getting an object first.
Source: https://github.com/jyasskin/web-bluetooth-1/commit/240dc987cc824fef692c8a561b7ad8afe6fcef93
WDYT @reillyeon?
> Expose all interfaces with user-visible instances

- index.bs
- index.html
By tagging with partial interface with [SecureContext] this API becomes
completely inaccessible from a non-secure context and so it is no longer
necessary to manually reject promises in getDevices() and
requestDevice().
> Use the [SecureContext] IDL attribute to enforce secure contexts.

- .travis.yml
- deploy.sh
This prevents the before_install step from failing on pull requests where the encrypted deploy key is not available.
> Move deploy_key description into deploy.sh.

- index.bs
The integration with the Feature Policy specification allows us to disallow (by default) access to this feature by cross-origin iframes with a standardized mechanism for the top-level document to grant access
to this feature to origins that it trusts.
With this mitigation in place the Allowed Origins descriptors are removed from the specification. This resolves the question in #49 of whether access to USB devices should be controlled by the vendor or the
user in the favor of the user.
This resolves issue #82 and obsoletes issues #15 and #38.
> Integrate with the Feature Policy specification

- index.bs
The special value 255 for bScheme indicates that the full URL should be
present in the URL field, allowing custom schemes unknown to this
specification.
This resolves issue #43.
> Add a special value for a custom scheme

- index.bs
There is no appropriate mailing list for developers to get support using the API (as opposed to contributing to the specification process). The best place for this is StackOverflow so this patch adds a link to the "webusb" tag.
Resolves issue #80.
> Add link to StackOverflow for developer support

- test/index.bs
This should resolve the issue specific to the Chromium implementation where it could be assumed that this method resets the state of the fakes synchronously.
> Make USBTest.reset() return a Promise

- index.bs
This new example covers opening, configuring and receiving data from a device. In the process I have improved the clarity of the algorithm for performing control, interrupt and bulk IN transfers.
Issue #89.
> Add an example of configuring and receiving data from a device

- index.bs
The syntax otherwise is invalid javascript.
> Add err argument to catch clause.

- test/index.bs
This change replaces the "lastFilters" and "chosenDevice" attributes with a "requestdevice" event that is fired when requestDevice() is called, allowing the test script to respondWith() the device it wants
the UA to simulate the user choosing.
This removes some synchronous behavior from the testing API and aligns better with patterns used elsewhere in the web platform.
> Use a "requestdevice" event for flexible request handling

- index.bs
```
dictionary USBPermissionStorage {
required sequence<AllowedUSBDevice> allowedDevices = [];
};
```
Isn't valid WebIDL syntax.  This patch removes the `required` directive.
> remove 'require' from USBPermissionStorage.allowedDevices, to correct WebIDL syntax (fixes #118)

- index.bs
This change to the spec will allow the WebUSB interface to be accessible within the context of a Web Worker.
I created an [explainer](https://github.com/odejesush/webusb-on-workers/blob/master/EXPLAINER.md) document for this addition.
Additionally, this feature was mentioned before in issue [WebUSB#73](https://github.com/WICG/webusb/issues/73).
I checked if the change to the IDL in chromium compiled successfully in change [1014196](https://chromium-review.googlesource.com/c/chromium/src/+/1014196).
Feedback on the change is welcome :)
> Allow WebUSB to be used within a Web Worker

- index.bs
- test/index.bs
This change fixes the build errors that we occurring due to unreferenced
definitions. The unreferenced definitions are changed to be &lt;strong&gt;&lt;em&gt;
blocks of text to have the same format. Other unreferenced definitions
were found references in the spec and manually linked.
> Fix build errors relating to unreferenced dfns

- .pr-preview.json
See https://github.com/tobie/pr-preview#configuration-file for documentation.
This only supports the main WebUSB specification. tobie/pr-preview#18 tracks being able to preview the testing spec as well.
> Add a PR-Preview configuration file

- index.bs
This change cleans up the device filter matching algorithm and reorders the steps so that the serial number (if part of the filter) is checked before attempting to match an interface. Otherwise the serial number will be ignored if an interface class is part of the filter.
This resolves issue 138.
***
<a href="https://pr-preview.s3.amazonaws.com/reillyeon/webusb/pull/139.html" title="Last updated on Jun 22, 2018, 5:14 PM GMT (3d21faa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/139/c8b978f...reillyeon:3d21faa.html" title="Last updated on Jun 22, 2018, 5:14 PM GMT (3d21faa)">Diff</a>
> Fix up device filter matching algorithm

- index.bs
- test/index.bs
Google, Inc. is now Google LLC. Added editor ID for Reilly Grant.
***
<a href="https://pr-preview.s3.amazonaws.com/reillyeon/webusb/pull/144.html" title="Last updated on Aug 23, 2018, 8:14 PM GMT (ccaef54)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/144/0e1df1e...reillyeon:ccaef54.html" title="Last updated on Aug 23, 2018, 8:14 PM GMT (ccaef54)">Diff</a>
> Update editors for WebUSB specs

- index.bs
- test/index.bs
This change updates the &lt;pre> tags for IDL definitions to be &lt;xmp> tags so that characters don't need to be escaped.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/webusb/pull/146.html" title="Last updated on Aug 24, 2018, 10:44 PM GMT (255c802)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/146/d7579c4...odejesush:255c802.html" title="Last updated on Aug 24, 2018, 10:44 PM GMT (255c802)">Diff</a>
> Update pre blocks to be xmp

- index.bs
The rules for encoding UUIDs in little-endian are esoteric and so this change adds a note with the correct formatting.
This resolves issue #115.
***
<a href="https://pr-preview.s3.amazonaws.com/reillyeon/webusb/pull/151.html" title="Last updated on Nov 9, 2018, 11:50 PM GMT (4cb7450)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/151/1ffc266...reillyeon:4cb7450.html" title="Last updated on Nov 9, 2018, 11:50 PM GMT (4cb7450)">Diff</a>
> Add a note about UUID endianness

- index.bs
These checks are incorrect as it is perfectly valid to issue a control transfer with `wLength` larger than `bMaxPacketSize0`. In this case the data stage of the control transfer will be split across multiple packets.
Resolves #155.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/pull/156.html" title="Last updated on Dec 7, 2018, 4:41 PM GMT (a24f4b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/156/433580b...a24f4b5.html" title="Last updated on Dec 7, 2018, 4:41 PM GMT (a24f4b5)">Diff</a>
> Remove bMaxPacketSize0 checks from control transfers

- index.bs
The current text seems like a typo.
***
<a href="https://pr-preview.s3.amazonaws.com/dsanders11/webusb-1/pull/160.html" title="Last updated on Dec 19, 2018, 8:04 PM UTC (4d3307a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/160/8442eb1...dsanders11:4d3307a.html" title="Last updated on Dec 19, 2018, 8:04 PM UTC (4d3307a)">Diff</a>
> Fix InvalidStateError condition for claimInterface

- index.bs
- test/index.bs
Algorithms for working with Promises have moved from [promises-guide] to [WebIDL].
***
<a href="https://pr-preview.s3.amazonaws.com/reillyeon/webusb/pull/175.html" title="Last updated on Sep 30, 2019, 5:41 PM UTC (fdf4ab1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/175/ab08225...reillyeon:fdf4ab1.html" title="Last updated on Sep 30, 2019, 5:41 PM UTC (fdf4ab1)">Diff</a>
> Migrate to references exported from the WebIDL spec

- index.bs
This change updates references to "user gesture" to use the new language
used for User Activation v2. The new language now states that the
requestDevice algorithm has to be triggered while its relevant global
object has a transient activation.
This fixes #178.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/webusb/pull/179.html" title="Last updated on Feb 11, 2020, 8:43 PM UTC (4dabd91)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/179/6400555...odejesush:4dabd91.html" title="Last updated on Feb 11, 2020, 8:43 PM UTC (4dabd91)">Diff</a>
> Update language for User Activation v2

- index.bs
- test/index.bs
This change updates the `Status` line to be `w3c/CG-DRAFT`. This fixes the
Travis CI build.
***
<a href="https://pr-preview.s3.amazonaws.com/odejesush/webusb/pull/182.html" title="Last updated on Feb 21, 2020, 5:52 PM UTC (c471a26)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/182/667004f...odejesush:c471a26.html" title="Last updated on Feb 21, 2020, 5:52 PM UTC (c471a26)">Diff</a>
> Use correct Status

- deploy.sh
This change makes errors in parsing a Bikeshed source file more visible
by adding color to the output and pointing out the file in which the
error occurred.
> Add more logging and colors to deploy.sh

- index.bs
Adds the `1. Let device be the target USBDevice object.` step to claimInterface.
***
<a href="https://pr-preview.s3.amazonaws.com/littledivy/webusb-spec/pull/202.html" title="Last updated on Sep 8, 2021, 10:33 PM UTC (ec2f91b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/202/55d24aa...littledivy:ec2f91b.html" title="Last updated on Sep 8, 2021, 10:33 PM UTC (ec2f91b)">Diff</a>
> Fix missing device target object in claimInterface

- test/index.bs
The test API is used for testing in both of these environments. This
change fixes WebIDL validation checks which now require interface
definitions to have an [Exposed] attribute.
> Expose the test API in Window and Worker

- index.bs
This list is already implemented by Chromium: https://groups.google.com/a/chromium.org/g/blink-dev/c/LZXocaeCwDw/m/GLfAffGLAAAJ
Fixes #201.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/pull/206.html" title="Last updated on Oct 6, 2021, 4:03 PM UTC (3b99c55)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/206/04c12b1...3b99c55.html" title="Last updated on Oct 6, 2021, 4:03 PM UTC (3b99c55)">Diff</a>
> Specify the protected interface class list

- index.bs
According to https://github.com/WICG/webusb/issues/208, we would like to enforce [SameObject] on attributes within the USBDevice object and its related object type.
In addition to adding [SameObject] enforcement and its related algorithm, refactor the touched sections to make their outline cleared.
***
<a href="https://pr-preview.s3.amazonaws.com/chengweih001/webusb/pull/212.html" title="Last updated on Feb 24, 2022, 12:35 AM UTC (8c52b30)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/212/80342de...chengweih001:8c52b30.html" title="Last updated on Feb 24, 2022, 12:35 AM UTC (8c52b30)">Diff</a>
> Support [SameObject] for related attributes within USBDevice

- index.bs
The new "exclusionFilters" option in `navigator.usb.requestDevice()` allows web developers to exclude some devices from the browser picker. It can be used to exclude devices that match a broader filter but are unsupported, or are already connected for instance.
```js
// Request access to a device from vendor ID 0xABCD. 
// The device with product ID 0x1234 has been reported as unsupported.
const device = await navigator.usb.requestDevice({
filters: [{ vendorId: 0xABCD }],
exclusionFilters: [{ vendorId: 0xABCD, productId: 0x1234 }],
});
```
Please have a look @reillyeon  
FIX: https://github.com/WICG/webusb/issues/232
***
<a href="https://pr-preview.s3.amazonaws.com/beaufortfrancois/webusb/pull/233.html" title="Last updated on Jun 19, 2023, 9:49 AM UTC (899dc84)">Preview</a> | <a …
> Add exclusionFilters to USBDeviceRequestOptions

- index.bs
As suggested in https://chromium-review.googlesource.com/c/chromium/src/+/4614682/15..16/third_party/blink/renderer/modules/webusb/usb.cc#b247, this PR sets the default value of `exclusionFilters` to `[]` to avoid differentiating between no list and an empty list.
@reillyeon please review.
Related to https://github.com/WICG/webusb/pull/233 and https://github.com/WICG/webusb/issues/232
***
<a href="https://pr-preview.s3.amazonaws.com/beaufortfrancois/webusb/pull/235.html" title="Last updated on Jun 23, 2023, 7:25 AM UTC (3656ec2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/235/1ebe98c...beaufortfrancois:3656ec2.html" title="Last updated on Jun 23, 2023, 7:25 AM UTC (3656ec2)">Diff</a>
> Add default value to exclusionFilters

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/pull/239.html" title="Last updated on Oct 11, 2023, 11:55 PM UTC (a256a3a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/239/2af4f14...a256a3a.html" title="Last updated on Oct 11, 2023, 11:55 PM UTC (a256a3a)">Diff</a>
> Add steps for parsing the blocklist and testing blocklistedness

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/nondebug/webusb/pull/238.html" title="Last updated on Oct 12, 2023, 12:43 AM UTC (d36b843)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/238/59614e7...nondebug:d36b843.html" title="Last updated on Oct 12, 2023, 12:43 AM UTC (d36b843)">Diff</a>
> Specify "usb-unrestricted" policy-controlled feature

- index.bs
In #221 we added specification text for how this API could be exposed to service workers but did not update the [Exposed] attribute in most of the WebIDL blocks. This updates the remaining blocks.
Fixed #249.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/pull/250.html" title="Last updated on Oct 4, 2024, 6:43 PM UTC (43478a5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/webusb/250/775f963...43478a5.html" title="Last updated on Oct 4, 2024, 6:43 PM UTC (43478a5)">Diff</a>
> Be consistent about worker interface exposure
